/**
 * Static registry of tracked institutional investors.
 * CIKs are zero-padded 10-digit SEC EDGAR identifiers for the 13F filing entity
 * (the fund/manager, NOT the company whose stock they hold).
 */

export type InstitutionCategory = "star" | "hedge_fund" | "tech_growth" | "asset_manager";

export interface Institution {
  id: string;             // URL-safe slug (numeric CIK without leading zeros)
  name: string;           // Fund / firm name
  manager: string;        // Lead portfolio manager
  cik: string;            // Zero-padded 10-digit CIK (as used in SEC API URLs)
  category: InstitutionCategory;
  description: string;
}

export const INSTITUTIONS: Institution[] = [
  // ── Star Investors ─────────────────────────────────────────────────────────
  {
    id: "1067983",
    name: "Berkshire Hathaway",
    manager: "Warren Buffett",
    cik: "0001067983",
    category: "star",
    description: "Value-focused diversified holding company",
  },
  {
    id: "1336528",
    name: "Pershing Square",
    manager: "Bill Ackman",
    cik: "0001336528",
    category: "star",
    description: "Concentrated activist long-only investor",
  },
  {
    id: "1649339",
    name: "Scion Asset Management",
    manager: "Michael Burry",
    cik: "0001649339",
    category: "star",
    description: "Contrarian value; famous for the 2008 subprime short",
  },
  {
    id: "1536411",
    name: "Duquesne Family Office",
    manager: "Stanley Druckenmiller",
    cik: "0001536411",
    category: "star",
    description: "Global macro and growth hybrid",
  },
  {
    id: "1656456",
    name: "Appaloosa Management",
    manager: "David Tepper",
    cik: "0001656456",
    category: "star",
    description: "Distressed debt and equity specialist",
  },
  {
    id: "1061768",
    name: "Baupost Group",
    manager: "Seth Klarman",
    cik: "0001061768",
    category: "star",
    description: "Deep value with strict margin-of-safety discipline",
  },
  {
    id: "1079114",
    name: "Greenlight Capital",
    manager: "David Einhorn",
    cik: "0001079114",
    category: "star",
    description: "Long/short value with activist roots",
  },
  {
    id: "1040273",
    name: "Third Point LLC",
    manager: "Dan Loeb",
    cik: "0001040273",
    category: "star",
    description: "Event-driven activist investor",
  },

  // ── Large Hedge Funds ───────────────────────────────────────────────────────
  {
    id: "1423689",
    name: "Citadel Advisors",
    manager: "Ken Griffin",
    cik: "0001423689",
    category: "hedge_fund",
    description: "Multi-strategy platform; ~$446B AUM",
  },
  {
    id: "1273087",
    name: "Millennium Management",
    manager: "Izzy Englander",
    cik: "0001273087",
    category: "hedge_fund",
    description: "Multi-strategy platform; ~$505B AUM",
  },
  {
    id: "1350694",
    name: "Bridgewater Associates",
    manager: "Ray Dalio",
    cik: "0001350694",
    category: "hedge_fund",
    description: "Global macro, All Weather strategies",
  },
  {
    id: "1037389",
    name: "Renaissance Technologies",
    manager: "Jim Simons",
    cik: "0001037389",
    category: "hedge_fund",
    description: "Quantitative systematic strategies",
  },
  {
    id: "1009207",
    name: "D.E. Shaw & Co",
    manager: "David Shaw",
    cik: "0001009207",
    category: "hedge_fund",
    description: "Systematic and quantitative multi-strategy",
  },
  {
    id: "1179392",
    name: "Two Sigma Investments",
    manager: "Overdeck & Siegel",
    cik: "0001179392",
    category: "hedge_fund",
    description: "Data-driven quantitative strategies",
  },
  {
    id: "1603466",
    name: "Point72 Asset Management",
    manager: "Steve Cohen",
    cik: "0001603466",
    category: "hedge_fund",
    description: "Multi-manager discretionary and quant",
  },
  {
    id: "1029997",
    name: "Soros Fund Management",
    manager: "George Soros",
    cik: "0001029997",
    category: "hedge_fund",
    description: "Global macro; legendary for 1992 Bank of England trade",
  },
  {
    id: "102909",
    name: "Vanguard Group",
    manager: "Salim Ramji",
    cik: "0000102909",
    category: "hedge_fund",
    description: "Index pioneer; $8T+ passive AUM",
  },

  // ── Tech-focused / Growth ───────────────────────────────────────────────────
  {
    id: "1167483",
    name: "Tiger Global Management",
    manager: "Chase Coleman",
    cik: "0001167483",
    category: "tech_growth",
    description: "Public and private tech-focused growth",
  },
  {
    id: "1418819",
    name: "Coatue Management",
    manager: "Philippe Laffont",
    cik: "0001418819",
    category: "tech_growth",
    description: "Technology-focused long/short equity",
  },
  {
    id: "1103804",
    name: "Viking Global Investors",
    manager: "Andreas Halvorsen",
    cik: "0001103804",
    category: "tech_growth",
    description: "Growth-oriented long/short equity",
  },

  // ── Large Asset Managers ────────────────────────────────────────────────────
  {
    id: "315066",
    name: "Fidelity (FMR LLC)",
    manager: "Abby Johnson",
    cik: "0000315066",
    category: "asset_manager",
    description: "One of the largest US asset managers; active and passive strategies",
  },
  {
    id: "80255",
    name: "T. Rowe Price",
    manager: "Rob Sharps",
    cik: "0000080255",
    category: "asset_manager",
    description: "Active growth-oriented manager; $1.9T AUM",
  },
  {
    id: "1214717",
    name: "Geode Capital Management",
    manager: "Robert Minicus",
    cik: "0001214717",
    category: "asset_manager",
    description: "Fidelity's indexing arm; $1.9T passive AUM",
  },
  {
    id: "902219",
    name: "Wellington Management",
    manager: "Jean Hynes",
    cik: "0000902219",
    category: "asset_manager",
    description: "Private partnership; $1.3T AUM across equities and fixed income",
  },
  {
    id: "354204",
    name: "Dimensional Fund Advisors",
    manager: "Dave Butler",
    cik: "0000354204",
    category: "asset_manager",
    description: "Factor-based systematic strategies; $835B AUM",
  },
  {
    id: "914208",
    name: "Invesco",
    manager: "Andrew Schlossberg",
    cik: "0000914208",
    category: "asset_manager",
    description: "Active and passive; $2.2T AUM including PowerShares ETFs",
  },
  {
    id: "38777",
    name: "Franklin Templeton",
    manager: "Jenny Johnson",
    cik: "0000038777",
    category: "asset_manager",
    description: "Global active manager; $467B+ AUM across equities and fixed income",
  },
  {
    id: "1137774",
    name: "PGIM (Prudential)",
    manager: "David Hunt",
    cik: "0001137774",
    category: "asset_manager",
    description: "Prudential's asset management arm; $1.0T AUM",
  },
  {
    id: "912938",
    name: "MFS Investment Management",
    manager: "Mike Roberge",
    cik: "0000912938",
    category: "asset_manager",
    description: "Oldest US mutual fund company; $473B active equity and fixed income",
  },
  {
    id: "1890906",
    name: "Allspring Global Investments",
    manager: "Joseph Sullivan",
    cik: "0001890906",
    category: "asset_manager",
    description: "Spun out of Wells Fargo Asset Management in 2021; $457B AUM",
  },
  {
    id: "861177",
    name: "UBS Asset Management Americas",
    manager: "Suni Harford",
    cik: "0000861177",
    category: "asset_manager",
    description: "US arm of UBS's global asset management franchise",
  },
  {
    id: "1055964",
    name: "Nomura Asset Management",
    manager: "Junko Nakagawa",
    cik: "0001055964",
    category: "asset_manager",
    description: "Japan's largest asset manager; US equity and fixed income strategies",
  },
  {
    id: "1529735",
    name: "MetLife Investment Management",
    manager: "Steven Goulart",
    cik: "0001529735",
    category: "asset_manager",
    description: "Insurance-linked asset manager; $508B AUM",
  },
  {
    id: "1109448",
    name: "AllianceBernstein",
    manager: "Seth Bernstein",
    cik: "0001109448",
    category: "asset_manager",
    description: "Global active manager; $709B AUM in equities and fixed income",
  },

  // ── Concentrated Fundamental / Special Situations ───────────────────────────
  {
    id: "1697591",
    name: "CAS Investment Partners",
    manager: "CAS Partners",
    cik: "0001697591",
    category: "star",
    description: "Concentrated long-only; Westport CT-based value-oriented fund",
  },
  {
    id: "1316622",
    name: "Redwood Capital Management",
    manager: "Jonathan Kolatch",
    cik: "0001316622",
    category: "hedge_fund",
    description: "Credit-focused event-driven; distressed debt and high-yield specialist",
  },
  {
    id: "1050464",
    name: "Peconic Partners",
    manager: "William Harnisch",
    cik: "0001050464",
    category: "star",
    description: "Long-term growth with global macro overlay; East Quogue NY-based",
  },
  {
    id: "1387322",
    name: "Whale Rock Capital",
    manager: "Alex Sacerdote",
    cik: "0001387322",
    category: "tech_growth",
    description: "Technology-focused long/short equity; Boston-based",
  },
  {
    id: "2045724",
    name: "Situational Awareness LP",
    manager: "Leopold Aschenbrenner",
    cik: "0002045724",
    category: "tech_growth",
    description: "AI infrastructure and power; ex-OpenAI researcher; $5.5B in equity positions",
  },
  {
    id: "1569049",
    name: "Light Street Capital",
    manager: "Glen Kacher",
    cik: "0001569049",
    category: "tech_growth",
    description: "Technology and media long/short; Menlo Park-based",
  },
  {
    id: "1647251",
    name: "TCI Fund Management",
    manager: "Chris Hohn",
    cik: "0001647251",
    category: "star",
    description: "Concentrated activist; London-based with large US tech and rail positions",
  },
  {
    id: "1503174",
    name: "SRS Investment Management",
    manager: "Karthik Sarma",
    cik: "0001503174",
    category: "star",
    description: "Ultra-concentrated long-term value; famous for decade-long Verisk hold",
  },
  {
    id: "1537530",
    name: "SCGE Management",
    manager: "Jeff Wang",
    cik: "0001537530",
    category: "tech_growth",
    description: "Sequoia Capital Global Equities; growth-focused public equity arm of Sequoia",
  },
  {
    id: "1697868",
    name: "Valley Forge Capital",
    manager: "Dev Kantesaria",
    cik: "0001697868",
    category: "star",
    description: "Ultra-concentrated quality growth; financial infrastructure and data businesses",
  },
  {
    id: "1631664",
    name: "Punch Card Management",
    manager: "Norbert Lou",
    cik: "0001631664",
    category: "star",
    description: "Ultra-concentrated value; rarely holds more than 5 positions",
  },
  {
    id: "1088875",
    name: "Baillie Gifford",
    manager: "Andrew Storar",
    cik: "0001088875",
    category: "asset_manager",
    description: "Scottish long-term growth investor; early backer of Amazon, Tesla, Moderna",
  },
  {
    id: "1541617",
    name: "Altimeter Capital",
    manager: "Brad Gerstner",
    cik: "0001541617",
    category: "tech_growth",
    description: "Concentrated tech-focused growth; famous for Airbnb, Snowflake, Meta positions",
  },
  {
    id: "1964171",
    name: "Deepwater Asset Management",
    manager: "Gene Munster",
    cik: "0001964171",
    category: "tech_growth",
    description: "Tech-focused long/short; founded by ex-Piper Sandler analyst Gene Munster",
  },
  {
    id: "2016708",
    name: "Niles Investment Management",
    manager: "Dan Niles",
    cik: "0002016708",
    category: "tech_growth",
    description: "Satori Fund; tech-focused long/short; $131M AUM as of Q4 2025",
  },
  {
    id: "923093",
    name: "Tudor Investment Corp",
    manager: "Paul Tudor Jones",
    cik: "0000923093",
    category: "hedge_fund",
    description: "Global macro pioneer; discretionary and systematic multi-strategy",
  },
  {
    id: "1709323",
    name: "Himalaya Capital",
    manager: "Li Lu",
    cik: "0001709323",
    category: "star",
    description: "Concentrated value; Charlie Munger's protégé; deep expertise in Asian markets",
  },
  {
    id: "1697748",
    name: "ARK Investment Management",
    manager: "Cathie Wood",
    cik: "0001697748",
    category: "tech_growth",
    description: "Disruptive innovation ETFs; ARKK flagship holds genomics, AI, fintech, space",
  },
  {
    id: "1595888",
    name: "Jane Street Group",
    manager: "Quant / Market Making",
    cik: "0001595888",
    category: "hedge_fund",
    description: "Quantitative market maker; massive ETF and options book — expect thousands of positions",
  },
  {
    id: "1777813",
    name: "Atreides Management",
    manager: "Gavin Baker",
    cik: "0001777813",
    category: "tech_growth",
    description: "Technology-focused growth; former Fidelity OTC Fund manager; Boston-based",
  },
  {
    id: "1747057",
    name: "D1 Capital Partners",
    manager: "Dan Sundheim",
    cik: "0001747057",
    category: "hedge_fund",
    description: "Long/short equity; ex-Viking Global CIO; $10B+ AUM",
  },
  {
    id: "1566887",
    name: "Ratan Capital",
    manager: "Ratan Capital Partners",
    cik: "0001566887",
    category: "hedge_fund",
    description: "Multi-strategy growth; Miami-based; top holdings include NVDA, META, AMZN",
  },
  {
    id: "850529",
    name: "Fisher Investments",
    manager: "Ken Fisher",
    cik: "0000850529",
    category: "asset_manager",
    description: "Global equity manager; $293B AUM; contrarian macro-driven approach",
  },
];

// ── UI metadata ─────────────────────────────────────────────────────────────

export const CATEGORY_META: Record<
  InstitutionCategory,
  { label: string; textColor: string; badgeCls: string }
> = {
  star: {
    label: "Star Investor",
    textColor: "text-amber-400",
    badgeCls: "bg-amber-400/10 border border-amber-400/25 text-amber-400",
  },
  hedge_fund: {
    label: "Hedge Fund",
    textColor: "text-sky-400",
    badgeCls: "bg-sky-400/10 border border-sky-400/25 text-sky-400",
  },
  tech_growth: {
    label: "Tech / Growth",
    textColor: "text-violet-400",
    badgeCls: "bg-violet-400/10 border border-violet-400/25 text-violet-400",
  },
  asset_manager: {
    label: "Asset Manager",
    textColor: "text-teal-400",
    badgeCls: "bg-teal-400/10 border border-teal-400/25 text-teal-400",
  },
};

export const ALL_CATEGORIES: InstitutionCategory[] = ["star", "hedge_fund", "tech_growth", "asset_manager"];
